=== googlecode-mirror/candydolldb/candydolldb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Models" type="ModelsType">
	<xs:unique name="uniqueModelName"> 
		<xs:selector xpath="./Model"/> 
		<xs:field xpath="@firstname"/>
		<xs:field xpath="@lastname"/> 
	</xs:unique>
</xs:element>

<!-- ================================================================== -->

<xs:simpleType name="Name">
	<xs:restriction base="xs:string">
		<xs:minLength value="1"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="MultiDate">
	<xs:list itemType="xs:date" />
</xs:simpleType>

<xs:simpleType name="EmptyName">
	<xs:union memberTypes="Empty Name"  />
</xs:simpleType>

<xs:simpleType name="EmptyDate">
	<xs:union memberTypes="Empty xs:date"  />
</xs:simpleType>

<xs:simpleType name="EmptyMultiDate">
	<xs:union memberTypes="Empty MultiDate"  />
</xs:simpleType>

<xs:simpleType name="Empty">
	<xs:restriction base="xs:string">
		<xs:enumeration value=""/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="DigitName">
	<xs:restriction base="xs:string">
		<xs:pattern value="([a-zA-Z0-9_])*(0?0[1-9]|0?[1-9][0-9]|[1-9][0-9][0-9])"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="EmptyHex32">
	<xs:union memberTypes="Empty Hex32"  />
</xs:simpleType>

<xs:simpleType name="Hex32">
	<xs:restriction base="xs:string">
		<xs:pattern value="([a-fA-F0-9]){32}" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="EmptyCSV">
	<xs:union memberTypes="Empty CSV"  />
</xs:simpleType>

<xs:simpleType name="CSV">
	<xs:restriction base="xs:string">
		<xs:pattern value="([^,]+(,[^,]+)*)" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ExtensionsImage">
	<xs:restriction base="xs:string">
		<xs:enumeration value="jpg"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ExtensionsVideo">
	<xs:restriction base="xs:string">
		<xs:enumeration value="wmv"/>
		<xs:enumeration value="mp4"/>
	</xs:restriction>
</xs:simpleType>

<!-- ================================================================== -->

<xs:complexType name="ModelsType">
	<xs:sequence>
		<xs:element name="Model" minOccurs="0" maxOccurs="unbounded" type="ModelType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ModelType" mixed="true">
	<xs:sequence>
		<xs:element name="Sets" minOccurs="0" maxOccurs="1" type="SetsType">
			<xs:unique name="uniqueSetName">
				<xs:selector xpath="./Set"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="Remarks" minOccurs="0" maxOccurs="1" type="xs:string" />
	</xs:sequence>

	<xs:attribute name="firstname" type="Name" use="required"/>
	<xs:attribute name="lastname" type="EmptyName" use="optional" default=""/>
	<xs:attribute name="birthdate" type="EmptyDate" use="optional" default=""/>
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>	
</xs:complexType>

<xs:complexType name="SetsType">
	<xs:sequence>
		<xs:element name="Set" minOccurs="1" maxOccurs="unbounded" type="SetType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="SetType">
	
	<xs:all>
		<xs:element name="Images" minOccurs="0" maxOccurs="1" type="ImagesType">
			<xs:unique name="uniqueImageName">
				<xs:selector xpath="./Image"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="Videos" minOccurs="0" maxOccurs="1" type="VideosType">
			<xs:unique name="uniqueVideoName">
				<xs:selector xpath="./Video"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
	</xs:all>

	<xs:attribute name="name" type="DigitName" use="required" />
	<xs:attribute name="date_pic" type="EmptyMultiDate" use="optional" default=""/>
	<xs:attribute name="date_vid" type="EmptyMultiDate" use="optional" default=""/>
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>

<xs:complexType name="ImagesType">
	<xs:sequence>
		<xs:element name="Image" minOccurs="1" maxOccurs="unbounded" type="ImageType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ImageType">
	<xs:attribute name="name" type="Name" use="required" />
	<xs:attribute name="extension" type="ExtensionsImage" use="required" />
	<xs:attribute name="filesize" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="checksum" type="EmptyHex32" use="required" />
	<xs:attribute name="width" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="height" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>

<xs:complexType name="VideosType">
	<xs:sequence>
		<xs:element name="Video" minOccurs="1" maxOccurs="unbounded" type="VideoType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="VideoType">
	<xs:attribute name="name" type="Name" use="required" />
	<xs:attribute name="extension" type="ExtensionsVideo" use="required" />
	<xs:attribute name="filesize" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="checksum" type="EmptyHex32" use="required" />
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>
   
</xs:schema>

=== googlecode-mirror/candydolldb/misc/2012_10_12.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="09" date_pic="" date_vid="2012-10-12" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Diana" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="06" date_pic="2012-10-12" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="15" date_pic="2012-10-12" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-09-14" date_vid="2012-10-12" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="23" date_pic="2012-09-21" date_vid="2012-10-12" tags=""/>
			<Set name="26" date_pic="2012-10-12" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Lauren" lastname="F" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-10-12" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Maryam" lastname="K" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-10-12" date_vid="2012-10-05" tags=""/>
		</Sets>
	</Model>

	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="106" date_pic="2012-10-12" date_vid="2012-07-06" tags=""/>
			<Set name="118" date_pic="" date_vid="2012-10-12" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_08_17.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">
	<Model firstname="Abrora" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="06" date_pic="2012-08-17" date_vid="2012-07-13" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="15" date_pic="2012-08-17" date_vid="2012-08-03" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="13" date_pic="2012-08-17" date_vid="2012-07-20" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="18" date_pic="2012-08-03" date_vid="2012-08-17" tags=""/>
			<Set name="19" date_pic="2012-08-17" date_vid="" tags=""/>
		</Sets>
	</Model>	
	<Model firstname="Lexi" lastname="G" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-07-27" date_vid="2012-08-17" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Marina" lastname="T" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="" date_vid="2012-08-17" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Suisan" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-08-17" tags=""/>
		</Sets>
	</Model>
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="98" date_pic="2012-08-17" date_vid="2012-05-11" tags=""/>
			<Set name="112" date_pic="" date_vid="2012-08-17" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Promotions">
		<Sets>
			<Set name="Sample06"/>
		</Sets>
	</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_11_23.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">
	<Model firstname="Adelina" lastname="N" birthdate="2002-05-05" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-23" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="11" date_pic="2012-11-23" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="08" date_pic="2012-11-09" date_vid="2012-11-23" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Eva" lastname="R" birthdate="2001-07-27" tags="">
		<Sets>
			<Set name="02" date_pic="2012-11-16" date_vid="2012-11-23" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="07" date_pic="2012-11-23" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="26" date_pic="2012-10-12" date_vid="2012-11-23" tags="blue, bracelet, chair, diadem, earrings, red drapes, ring, white socks"/>
		</Sets>
	</Model>
	<Model firstname="Lauren" lastname="F" birthdate="2001-04-25" tags="">
		<Sets>
			<Set name="02" date_pic="2012-11-23" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="12" date_pic="2012-11-02" date_vid="2012-11-23" tags=""/>
		</Sets>
	</Model>
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="112" date_pic="2012-11-23" date_vid="2012-08-17" tags=""/>
			<Set name="124" date_pic="" date_vid="2012-11-23" tags=""/>
		</Sets>
	</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_11_30.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="09" date_pic="" date_vid="2012-11-30" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Bianca" lastname="M" birthdate="1998-09-26" tags="">
		<Sets>
			<Set name="02" date_pic="" date_vid="2012-11-30" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Eva" lastname="R" birthdate="2001-07-27" tags="">
		<Sets>
			<Set name="03" date_pic="2012-11-30" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Jessica" lastname="C" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="" date_vid="2012-11-30" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="28" date_pic="2012-11-30" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Maryam" lastname="K" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="2012-11-30" date_vid="2012-11-16" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Sofi" lastname="E" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-30" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Yuliana" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-16" date_vid="2012-11-30" tags=""/>
		</Sets>
	</Model>
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="113" date_pic="2012-11-30" date_vid="2012-08-24" tags=""/>
			<Set name="125" date_pic="" date_vid="2012-11-30" tags=""/>
		</Sets>
	</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_11_09.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="22" date_pic="" date_vid="2012-11-09" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="10" date_pic="" date_vid="2012-11-09" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="08" date_pic="2012-11-09" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Diana" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="08" date_pic="2012-11-09" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Eva" lastname="R" birthdate="2001-07-27" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-09" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Khloe" lastname="R" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-10-26" date_vid="2012-11-09" tags="chair, cupboard, curls, diadem, mirror, pink, wood floor"/>
		</Sets>
	</Model>
	
	<Model firstname="Lesya" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-11-09" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Suisan" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="03" date_pic="2012-11-09" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="110" date_pic="2012-11-09" date_vid="2012-08-03" tags=""/>
			<Set name="122" date_pic="" date_vid="2012-11-09" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/promo-content.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candydolldb.xsd" xmlns="">
<Model firstname="Promotions" lastname="" birthdate="" tags="">
	<Sets>
		<Set name="Promotion01" date_pic="" date_vid="" tags="Oksana02, LarisaH07, Catsute01, ValeriaL12, SvetlanaT04, VictoriaD01, SP_Bloomers01, UlyanaM03, VictoriaS01, SashaL01, SP_Alice01, KaterynaV01, SP_Sailor01, SP_Alice02, UlyanaA02, SvetlanaT05, LarisaH01, SP_Housemaid01, VictoriaD02, ValeriaL01, YuliyaS01, KaterynaV02, SvetlanaT01"/>
		<Set name="Promotion02" date_pic="" date_vid="" tags="ValeriyaL02, ValeriyaL07, KaterynaV06, ValeriyaL03, AnnaT08, AnnaT02, IrynaM05, AnnaT09, IrynaM02, SashaD03, Sashal08, SashaL04, YuliyaS02, VictoriaD04, AnastasiaS01, SvetlanaT03, LarisaH04, SashaD07, AlinaG03, UlyanaM02, YuliyaS03, SashaD06, AlinaG01, OlgaS01, AnnaZ05, YuliyaZ03, OlgaS02, AnnaT01, AnnaT03, AlinaG07(missing), AnastasiaS06, ValeriyaL08, SashaD01, SashaD02, AnnaZ01, AlinaG06, AnnaT05(missing), UlyanaM06, YuliyaS10, ValeriyaL05, Valeriya06(missing), UlyanaM07, SashaL02"/>
		<Set name="Promotion03" date_pic="" date_vid="" tags="MashaS06, AlyonaR01, VikaZ02, JuliyaR03, IrinaB06"/>
		<Set name="Promotion04" date_pic="" date_vid="" tags="MashaS02, JuliyaR01, AlyonaR02, InnaL01, VikaZ06, AlyonaR06, JuliyaR04, MashaS01, AlyonaR05, VikaZ03, JuliyaR02"/>
		<Set name="Promotion05" date_pic="" date_vid="" tags="AlyonaR03, MashaP01, MashaS10, LeraC01, IrinaB01, OlyaY06, AlyonaR04, AlyonaG01, IrinaB04, AlyonaR03, OlyaY04, LeraC02"/>
		<Set name="Promotion06" date_pic="" date_vid="" tags="VikaZ07, AlyonaR09, MashaS08, InnaL10, IrinaB07, MashaS09"/>
		<Set name="Promotion07" date_pic="" date_vid="" tags="AlyonaR09, AnastasiaK02, InnaL09, VikaZ08, MashaP05, MashaS09, AnastasiaK04, AlyonaR08"/>
		<Set name="Promotion08" date_pic="" date_vid="" tags="AnjelikaL01, MonikaD01, PionaP01, ElisaM01, NinaT01, BiyankaS01, OlyaY11, IrinaB10, SonyaM01, MashaS11"/>
		<Set name="Promotion09" date_pic="" date_vid="" tags="BiyankaS01, VioletaK02, ElizabetaS02, OlyaY12, PionaP02, VikaZ12, SonyaM02, AlyonaR11, AnjelikaL02"/>
		<Set name="Promotion10" date_pic="" date_vid="" tags="VikaZ13, MargaritaD04, AnjelikaL04, VioletaK04, OlyaY13, PionaP04, SofiyaY03, ElizabetaS05, PionaP05, VikaZ14, ElizabetaS03, MashaS13, SonyaM03"/>
		<Set name="Promotion11" date_pic="" date_vid="" tags="AnjelikaL06, VioletaK06, VioletaK07, MonikaD06, OlyaY14, PionaP06, BiyankaS04, ElisaM04, MonikaD07, AnjelikaL08, AlyonaR13, MashaS14, ElizabetaS06"/>
		<Set name="Promotion12" date_pic="" date_vid="" tags="VioletaK09, ElizabetaS09, VikaZ18, IrinaB14, ElisaM05, MashaS15, VikaZ20, RitaK05, BiyankaS05, ElizabetaS10, PionaP10, VikaZ19, MonikaD09, NinaT05, VioletaK10"/>
		<Set name="Promotion13" date_pic="" date_vid="" tags="SharlottaS01, VikaZ21, LiliyaY01, MilenaS01, PionaP11, VioletaK11, LiliyaY02, LauraB02, AnjelikaL11, LauraB02"/>
		<Set name="Promotion14" date_pic="" date_vid="" tags="VikaZ22, LauraB04, MilenaS02, PionaP12, SyuzannaR02, SharlottaS04, JuliyaR11, LiliyaY03"/>
		<Set name="Promotion15" date_pic="" date_vid="" tags="ElizabetaS13, LiliyaY06, SharlottaS08, ZinaB03, VioletaK03, SilviyaR03, LauraB04, MilenaS03"/>
		<Set name="Promotion16" date_pic="" date_vid="" tags="VioletaK14, SharlottaS12, PionaP14, MilenaS04, MayaL04, LiliyaY07, JuliyaR13, ElizabetaS14, ElisaM09, SharlottaS11"/>
		<Set name="Promotion17" date_pic="" date_vid="" tags="SyuzannaR05, ZinaB05, ElizabetaS15, LiliyaY10, VikaZ25, SharlottaS15, PionaP15, MilenaS05, LauraB09"/>
		<Set name="Promotion18" date_pic="" date_vid="" tags="SonyaM07, SharlottaS17, LiliyaY07, ViolettaK16, MayaL06, AliceL01, EvaG01, AnitaD06, ElenaV01, SofiyaZ06, PionaP16, NatashaC03"/>
		<Set name="Promotion19" date_pic="" date_vid="" tags="NatashaC06, PionaP17, SonyaM11, SharlottaS18, SofiyaV07, LiliyaY12"/>
		<Set name="Promotion20" date_pic="" date_vid="" tags="SonyaM14, MayaL13, SharlottaS20, AnitaD08, SofiyaV08, LauraB13, AliceL03, PionaP18, NatashaC09"/>
		<Set name="Promotion21" date_pic="" date_vid="" tags="SonyaM16, MayaL16, AliceL04, LiliyaY14, VioletaK19, SharlottaS22, RitaK09, SofiyaV09, NatashaC10"/>
		<Set name="Promotion22" date_pic="" date_vid="" tags="EvaG05, LauraB15, LiliyaY15, AnitaD10, VikaZ30, PionaP20, BiyankaS10, SonyaM20, SharlottaS24, VioletaK20, NatashaC13"/>
		<Set name="Promotion23" date_pic="" date_vid="" tags="DianaM01, LiliyaY17, ChrisG01, ValensiyaS05, LinaI02, MayaL19, NatashaC14, LauraB17"/>
		<Set name="Promotion24" date_pic="" date_vid="" tags="LinaI04, ElisaM12, MayaL21, LiliyaY18, SanyaV03, LauraB18, EmmaM02, Valensiya14, DianaM02"/>
		<Set name="Promotion25" date_pic="" date_vid="" tags="LiliyaY21, ChrisG04, SarahK03, MarieA03, ElisaM13, AlyonaR17, SanyaV05, LauraB20, LinaI08"/>
		<Set name="Promotion26" date_pic="" date_vid="" tags="LauraB22, SanyaV07, AliceL12, SarahK04, MarieA04, NatashaC17, ElisaM14, MayaL25, ChrisG05, LiliyaY23, LinaI12"/>
		<Set name="Promotion27" date_pic="" date_vid="" tags="LauraB25, LiliyaY24, unknown (MayaL and LiliyaY in Cosplay), YuliyaK01, MayaL28, ValensiyaS26, LauraB24, unknown (LiliyaY, LauraB, ValensiyaS)"/>
		<Set name="Promotion28" date_pic="" date_vid="" tags="ValensiyaS29, Anjelika16, YuliyaK03, SofiyaV011, MariyaD01, AlisaA01, VikaZ31, LidiyaA01, LiliyaY27, LauraB26"/>
		<Set name="Promotion29" date_pic="" date_vid="" tags="LinaI14, EricaR02, LiliyaY28, VikaZ32, SanyaV10, YuliyaK04, ValensiyaS31, MayaL31"/>
		<Set name="Promotion30" date_pic="" date_vid="" tags="EricaR04, YuliyaK06, MayaL33, VikaZ33, LiliyaY29, LidiyaA04, VikaZ34, YuliyaK07"/>
		<Set name="Promotion31" date_pic="" date_vid="" tags="YuliyaK10, SofiyaV13, LinaI16, AnjelikaL19, YuliyaK08, ValensiyaS35, SanyaV11, DianaM08"/>
	</Sets>
</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_09_28.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="19" date_pic="2012-09-28" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="08" date_pic="2012-09-07" date_vid="2012-09-28" tags="bare feet, bikini, chair, earrings, ponytail, red drapes"/>
		</Sets>
	</Model>
	
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="07" date_pic="2012-09-28" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="21" date_pic="2012-08-31" date_vid="2012-09-28" tags="blue, braid, chair, hair flower, necklace, red drapes, white leggings"/>
			<Set name="24" date_pic="2012-09-28" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Kleo" lastname="M" birthdate="1999-08-16" tags="">
		<Sets>
			<Set name="05" date_pic="2012-07-20" date_vid="2012-09-28" tags="bodysuit, braid, red drapes"/>
		</Sets>
	</Model>

	<Model firstname="Mila" lastname="L" birthdate="1997-11-27" tags="">
		<Sets>
			<Set name="02" date_pic="2012-08-10" date_vid="2012-09-28" tags="bare feet, black, blue drapes, chair, pink"/>
		</Sets>
	</Model>
	
	<Model firstname="Nika" lastname="V" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-09-28" date_vid="2012-08-03" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="104" date_pic="2012-09-28" date_vid="2012-06-22" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_08_31.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="06" date_pic="2012-08-24" date_vid="2012-08-31" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="14" date_pic="2012-08-31" date_vid="2012-08-10" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="21" date_pic="2012-08-31" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Khloe" lastname="R" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-08-31" date_vid="2012-06-08" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Lexi" lastname="G" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-08-03" date_vid="2012-08-31" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="18" date_pic="" date_vid="2012-08-31" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Marina" lastname="T" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-08-31" date_vid="2012-08-17" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Maryam" lastname="K" birthdate="" tags="">
		<Sets>
			<Set name="03" date_pic="2012-07-20" date_vid="2012-08-31" tags="bare feet, blue, chair, ponytail, red drapes"/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="100" date_pic="2012-08-31" date_vid="2012-05-25" tags=""/>
			<Set name="114" date_pic="" date_vid="2012-08-31" tags=""/>
		</Sets>
	</Model>
</Models>
