=== googlecode-mirror/candydolldb/candydolldb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Models" type="ModelsType">
	<xs:unique name="uniqueModelName"> 
		<xs:selector xpath="./Model"/> 
		<xs:field xpath="@firstname"/>
		<xs:field xpath="@lastname"/> 
	</xs:unique>
</xs:element>

<!-- ================================================================== -->

<xs:simpleType name="Name">
	<xs:restriction base="xs:string">
		<xs:minLength value="1"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="MultiDate">
	<xs:list itemType="xs:date" />
</xs:simpleType>

<xs:simpleType name="EmptyName">
	<xs:union memberTypes="Empty Name"  />
</xs:simpleType>

<xs:simpleType name="EmptyDate">
	<xs:union memberTypes="Empty xs:date"  />
</xs:simpleType>

<xs:simpleType name="EmptyMultiDate">
	<xs:union memberTypes="Empty MultiDate"  />
</xs:simpleType>

<xs:simpleType name="Empty">
	<xs:restriction base="xs:string">
		<xs:enumeration value=""/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="DigitName">
	<xs:restriction base="xs:string">
		<xs:pattern value="([a-zA-Z0-9_])*(0?0[1-9]|0?[1-9][0-9]|[1-9][0-9][0-9])"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="EmptyHex32">
	<xs:union memberTypes="Empty Hex32"  />
</xs:simpleType>

<xs:simpleType name="Hex32">
	<xs:restriction base="xs:string">
		<xs:pattern value="([a-fA-F0-9]){32}" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="EmptyCSV">
	<xs:union memberTypes="Empty CSV"  />
</xs:simpleType>

<xs:simpleType name="CSV">
	<xs:restriction base="xs:string">
		<xs:pattern value="([^,]+(,[^,]+)*)" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ExtensionsImage">
	<xs:restriction base="xs:string">
		<xs:enumeration value="jpg"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ExtensionsVideo">
	<xs:restriction base="xs:string">
		<xs:enumeration value="wmv"/>
		<xs:enumeration value="mp4"/>
	</xs:restriction>
</xs:simpleType>

<!-- ================================================================== -->

<xs:complexType name="ModelsType">
	<xs:sequence>
		<xs:element name="Model" minOccurs="0" maxOccurs="unbounded" type="ModelType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ModelType" mixed="true">
	<xs:sequence>
		<xs:element name="Sets" minOccurs="0" maxOccurs="1" type="SetsType">
			<xs:unique name="uniqueSetName">
				<xs:selector xpath="./Set"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="Remarks" minOccurs="0" maxOccurs="1" type="xs:string" />
	</xs:sequence>

	<xs:attribute name="firstname" type="Name" use="required"/>
	<xs:attribute name="lastname" type="EmptyName" use="optional" default=""/>
	<xs:attribute name="birthdate" type="EmptyDate" use="optional" default=""/>
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>	
</xs:complexType>

<xs:complexType name="SetsType">
	<xs:sequence>
		<xs:element name="Set" minOccurs="1" maxOccurs="unbounded" type="SetType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="SetType">
	
	<xs:all>
		<xs:element name="Images" minOccurs="0" maxOccurs="1" type="ImagesType">
			<xs:unique name="uniqueImageName">
				<xs:selector xpath="./Image"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="Videos" minOccurs="0" maxOccurs="1" type="VideosType">
			<xs:unique name="uniqueVideoName">
				<xs:selector xpath="./Video"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
	</xs:all>

	<xs:attribute name="name" type="DigitName" use="required" />
	<xs:attribute name="date_pic" type="EmptyMultiDate" use="optional" default=""/>
	<xs:attribute name="date_vid" type="EmptyMultiDate" use="optional" default=""/>
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>

<xs:complexType name="ImagesType">
	<xs:sequence>
		<xs:element name="Image" minOccurs="1" maxOccurs="unbounded" type="ImageType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ImageType">
	<xs:attribute name="name" type="Name" use="required" />
	<xs:attribute name="extension" type="ExtensionsImage" use="required" />
	<xs:attribute name="filesize" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="checksum" type="EmptyHex32" use="required" />
	<xs:attribute name="width" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="height" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>

<xs:complexType name="VideosType">
	<xs:sequence>
		<xs:element name="Video" minOccurs="1" maxOccurs="unbounded" type="VideoType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="VideoType">
	<xs:attribute name="name" type="Name" use="required" />
	<xs:attribute name="extension" type="ExtensionsVideo" use="required" />
	<xs:attribute name="filesize" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="checksum" type="EmptyHex32" use="required" />
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>
   
</xs:schema>

=== googlecode-mirror/candydolldb/misc/2012_12_07.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="09" date_pic="2012-12-07" date_vid="2012-11-30" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Eva" lastname="R" birthdate="2001-07-27" tags="">
		<Sets>
			<Set name="04" date_pic="2012-12-07" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Lauren" lastname="F" birthdate="2001-04-25" tags="">
		<Sets>
			<Set name="03" date_pic="" date_vid="2012-12-07" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Lesya" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-12-07" date_vid="2012-11-09" tags=""/>
			<Set name="02" date_pic="" date_vid="2012-12-07" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Nika" lastname="V" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-10-05" date_vid="2012-12-07" tags="bracelet, chair, diadem, earrings, pink, red drapes"/>
		</Sets>
	</Model>
	<Model firstname="Sofi" lastname="E" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-30" date_vid="2012-12-07" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Yuliana" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-12-07" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Promotions" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="Sample09" date_pic="" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="114" date_pic="2012-12-07" date_vid="2012-08-31" tags=""/>
			<Set name="126" date_pic="" date_vid="2012-12-07" tags=""/>
		</Sets>
	</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_09_07.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="08" date_pic="2012-09-07" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Diana" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="2012-09-07" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="15" date_pic="" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="19" date_pic="2012-08-17" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Margaret" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="2012-08-10" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="10" date_pic="2012-09-07" date_vid="2012-07-27" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="16" date_pic="2012-09-07" date_vid="2012-08-10" tags=""/>
			<Set name="19" date_pic="" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="101" date_pic="2012-09-07" date_vid="2012-06-01" tags=""/>
			<Set name="115" date_pic="" date_vid="2012-09-07" tags=""/>
		</Sets>
	</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_10_05.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="20" date_pic="2012-10-05" date_vid="2012-09-14" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Diana" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="2012-09-07" date_vid="2012-10-05" tags="bare feet, bunny ears, red drapes, yellow"/>
		</Sets>
	</Model>
	
	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="03" date_pic="2012-07-27" date_vid="2010-10-05" tags="black shoes, chair, diadem, gloves, maid, red drapes, white stockings"/>
		</Sets>
	</Model>
	
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="22" date_pic="2012-09-14" date_vid="2010-10-05" tags=""/>
			<Set name="25" date_pic="2012-10-05" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Khloe" lastname="R" birthdate="" tags="">
		<Sets>
			<Set name="03" date_pic="2012-10-05" date_vid="2012-06-22" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Maryam" lastname="K" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="" date_vid="2012-10-05" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Nika" lastname="V" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-10-05" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="105" date_pic="2012-10-05" date_vid="2012-06-29" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_11_16.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="23" date_pic="" date_vid="2012-11-16" tags=""/>			
		</Sets>
	</Model>
	
	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="10" date_pic="2012-11-16" date_vid="2012-11-09" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Diana" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="09" date_pic="2012-11-16" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Elona" lastname="V" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="" date_vid="2012-11-16" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Eva" lastname="R" birthdate="2001-07-27" tags="">
		<Sets>
			<Set name="02" date_pic="2012-11-16" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Jessica" lastname="C" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-11-16" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Maryam" lastname="K" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="" date_vid="2012-11-16" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Yuliana" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-16" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="111" date_pic="2012-11-16" date_vid="2012-08-10" tags=""/>
			<Set name="123" date_pic="" date_vid="2012-11-16" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_08_10.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candydolldb.xsd" xmlns="">
	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="16" date_pic="" date_vid="2012-08-10" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="05" date_pic="2012-08-10" date_vid="2012-07-20" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="14" date_pic="" date_vid="2012-08-10" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-07-06" date_vid="2012-08-10" tags="black bodysuit, blue carpet, chair, hair barrette, hair buns, red drapes, slippers"/>
		</Sets>
	</Model>
	<Model firstname="Kleo" lastname="M" birthdate="1999-08-16" tags="">
		<Sets>
			<Set name="04" date_pic="2012-06-08" date_vid="2012-08-10" tags="bare feet, bikini, chair, polkadot, red drapes, striped"/>
		</Sets>
	</Model>
	<Model firstname="Margaret" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="2012-08-10" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Mila" lastname="L" birthdate="1997-11-27" tags="">
		<Sets>
			<Set name="02" date_pic="2012-08-10" date_vid="" tags=""/>
		</Sets>
	</Model>
	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="08" date_pic="2012-08-10" date_vid="2012-06-29" tags=""/>
		</Sets>
	</Model>
</Models>

=== googlecode-mirror/candydolldb/misc/2012_09_21.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="18" date_pic="2012-09-21" date_vid="2012-08-31" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="07" date_pic="2012-07-13" date_vid="2012-09-21" tags="blue stockings, chair, earrings, hair band, lace, red drapes, white"/>
		</Sets>
	</Model>
	
	<Model firstname="Diana" lastname="H" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-07-13" date_vid="2012-09-21" tags="bare feet, bikini, chair, earrings, red drapes, skipping rope"/>
		</Sets>
	</Model>
	
	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="05" date_pic="2012-09-21" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="23" date_pic="2012-09-21" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Margaret" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="07" date_pic="" date_vid="2012-09-21" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="11" date_pic="2012-09-14" date_vid="2012-09-21" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Suisan" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-09-21" date_vid="2012-08-17" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="103" date_pic="2012-09-21" date_vid="2012-06-15" tags=""/>
			<Set name="117" date_pic="" date_vid="2012-09-21" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_11_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Adelina" lastname="N" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="21" date_pic="2012-11-02" date_vid="2012-10-19" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Bianca" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-11-02" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Elona" lastname="V" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="17" date_pic="" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="06" date_pic="2012-11-02" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Lauren" lastname="F" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="12" date_pic="2012-11-02" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="109" date_pic="2012-11-02" date_vid="2012-07-27" tags=""/>
			<Set name="121" date_pic="" date_vid="2012-11-02" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_09_14.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="17" date_pic="2012-09-14" date_vid="2012-08-24" tags=""/>
			<Set name="20" date_pic="" date_vid="2012-09-14" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="06" date_pic="" date_vid="2012-09-14" tags="" />
		</Sets>
	</Model>
	
	<Model firstname="Isabella" lastname="B" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-09-14" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="20" date_pic="2012-08-24" date_vid="2012-09-14" tags="black, black shoes, chair, earrings, hair feather, pink, red drapes, white socks"/>
			<Set name="22" date_pic="2012-09-14" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Margaret" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="06" date_pic="2012-08-24" date_vid="2012-09-14" tags="bare feet, chair, earrings, red drapes, white, white shorts"/>
		</Sets>
	</Model>
	
	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="11" date_pic="2012-09-14" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="102" date_pic="2012-09-14" date_vid="2012-06-08" tags=""/>
			<Set name="116" date_pic="" date_vid="2012-09-14" tags=""/>
		</Sets>
	</Model>
	
</Models>
