=== googlecode-mirror/candydolldb/candydolldb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Models" type="ModelsType">
	<xs:unique name="uniqueModelName"> 
		<xs:selector xpath="./Model"/> 
		<xs:field xpath="@firstname"/>
		<xs:field xpath="@lastname"/> 
	</xs:unique>
</xs:element>

<!-- ================================================================== -->

<xs:simpleType name="Name">
	<xs:restriction base="xs:string">
		<xs:minLength value="1"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="MultiDate">
	<xs:list itemType="xs:date" />
</xs:simpleType>

<xs:simpleType name="EmptyName">
	<xs:union memberTypes="Empty Name"  />
</xs:simpleType>

<xs:simpleType name="EmptyDate">
	<xs:union memberTypes="Empty xs:date"  />
</xs:simpleType>

<xs:simpleType name="EmptyMultiDate">
	<xs:union memberTypes="Empty MultiDate"  />
</xs:simpleType>

<xs:simpleType name="Empty">
	<xs:restriction base="xs:string">
		<xs:enumeration value=""/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="DigitName">
	<xs:restriction base="xs:string">
		<xs:pattern value="([a-zA-Z0-9_])*(0?0[1-9]|0?[1-9][0-9]|[1-9][0-9][0-9])"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="EmptyHex32">
	<xs:union memberTypes="Empty Hex32"  />
</xs:simpleType>

<xs:simpleType name="Hex32">
	<xs:restriction base="xs:string">
		<xs:pattern value="([a-fA-F0-9]){32}" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="EmptyCSV">
	<xs:union memberTypes="Empty CSV"  />
</xs:simpleType>

<xs:simpleType name="CSV">
	<xs:restriction base="xs:string">
		<xs:pattern value="([^,]+(,[^,]+)*)" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ExtensionsImage">
	<xs:restriction base="xs:string">
		<xs:enumeration value="jpg"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="ExtensionsVideo">
	<xs:restriction base="xs:string">
		<xs:enumeration value="wmv"/>
		<xs:enumeration value="mp4"/>
	</xs:restriction>
</xs:simpleType>

<!-- ================================================================== -->

<xs:complexType name="ModelsType">
	<xs:sequence>
		<xs:element name="Model" minOccurs="0" maxOccurs="unbounded" type="ModelType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ModelType" mixed="true">
	<xs:sequence>
		<xs:element name="Sets" minOccurs="0" maxOccurs="1" type="SetsType">
			<xs:unique name="uniqueSetName">
				<xs:selector xpath="./Set"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="Remarks" minOccurs="0" maxOccurs="1" type="xs:string" />
	</xs:sequence>

	<xs:attribute name="firstname" type="Name" use="required"/>
	<xs:attribute name="lastname" type="EmptyName" use="optional" default=""/>
	<xs:attribute name="birthdate" type="EmptyDate" use="optional" default=""/>
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>	
</xs:complexType>

<xs:complexType name="SetsType">
	<xs:sequence>
		<xs:element name="Set" minOccurs="1" maxOccurs="unbounded" type="SetType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="SetType">
	
	<xs:all>
		<xs:element name="Images" minOccurs="0" maxOccurs="1" type="ImagesType">
			<xs:unique name="uniqueImageName">
				<xs:selector xpath="./Image"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
		<xs:element name="Videos" minOccurs="0" maxOccurs="1" type="VideosType">
			<xs:unique name="uniqueVideoName">
				<xs:selector xpath="./Video"/>
				<xs:field xpath="@name"/>
			</xs:unique>
		</xs:element>
	</xs:all>

	<xs:attribute name="name" type="DigitName" use="required" />
	<xs:attribute name="date_pic" type="EmptyMultiDate" use="optional" default=""/>
	<xs:attribute name="date_vid" type="EmptyMultiDate" use="optional" default=""/>
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>

<xs:complexType name="ImagesType">
	<xs:sequence>
		<xs:element name="Image" minOccurs="1" maxOccurs="unbounded" type="ImageType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="ImageType">
	<xs:attribute name="name" type="Name" use="required" />
	<xs:attribute name="extension" type="ExtensionsImage" use="required" />
	<xs:attribute name="filesize" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="checksum" type="EmptyHex32" use="required" />
	<xs:attribute name="width" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="height" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>

<xs:complexType name="VideosType">
	<xs:sequence>
		<xs:element name="Video" minOccurs="1" maxOccurs="unbounded" type="VideoType" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="VideoType">
	<xs:attribute name="name" type="Name" use="required" />
	<xs:attribute name="extension" type="ExtensionsVideo" use="required" />
	<xs:attribute name="filesize" type="xs:nonNegativeInteger" use="required" />
	<xs:attribute name="checksum" type="EmptyHex32" use="required" />
	<xs:attribute name="tags" type="EmptyCSV" use="optional" default=""/>
</xs:complexType>
   
</xs:schema>

=== googlecode-mirror/candydolldb/misc/2012_10_26.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Anastasia" lastname="R" birthdate="1999-04-03" tags="">
		<Sets>
			<Set name="09" date_pic="2012-10-26" date_vid="2012-10-12" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Bianca" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Eva" lastname="R" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Hanna" lastname="F" birthdate="2002-04-22" tags="">
		<Sets>
			<Set name="16" date_pic="" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="25" date_pic="2012-10-05" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Khloe" lastname="R" birthdate="" tags="">
		<Sets>
			<Set name="04" date_pic="2012-10-26" date_vid="" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Lauren" lastname="F" birthdate="" tags="">
		<Sets>
			<Set name="01" date_pic="2012-10-26" date_vid="2012-10-12" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="Nika" lastname="V" birthdate="" tags="">
		<Sets>
			<Set name="03" date_pic="2012-10-26" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="108" date_pic="2012-10-26" date_vid="2012-07-20" tags=""/>
			<Set name="120" date_pic="" date_vid="2012-10-26" tags=""/>
		</Sets>
	</Model>
	
</Models>

=== googlecode-mirror/candydolldb/misc/2012_08_24.xml
<?xml version="1.0" encoding="UTF-8"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../candydolldb.xsd" xmlns="">

	<Model firstname="Bella" lastname="K" birthdate="1999-04-11" tags="">
		<Sets>
			<Set name="06" date_pic="2012-08-24" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Katie" lastname="M" birthdate="2001-12-18" tags="">
		<Sets>
			<Set name="20" date_pic="2012-08-24" date_vid="" tags=""/>
		</Sets>
	</Model>	
	
	<Model firstname="Margaret" lastname="M" birthdate="" tags="">
		<Sets>
			<Set name="06" date_pic="2012-08-24" date_vid="" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Sabina" lastname="C" birthdate="2001-06-25" tags="">
		<Sets>
			<Set name="09" date_pic="2012-08-24" date_vid="2012-07-06" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Alissa" lastname="P" birthdate="2003-08-20" tags="">
		<Sets>
			<Set name="17" date_pic="" date_vid="2012-08-24" tags=""/>
		</Sets>
	</Model>

	<Model firstname="Maryam" lastname="K" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="2012-07-06" date_vid="2012-08-24" tags="bloomers, blue carpet, blue shoes, chair, hair barrette, hair ties, ponytail, red drapes, ringer t-shirt, skipping rope, striped socks"/>
		</Sets>
	</Model>

	<Model firstname="Mila" lastname="L" birthdate="1997-11-27" tags="">
		<Sets>
			<Set name="01" date_pic="2012-06-15" date_vid="2012-08-24" tags="black, black shoes, blue drapes, chair, maid, white, white stockings"/>
		</Sets>
	</Model>

	<Model firstname="Suisan" lastname="A" birthdate="" tags="">
		<Sets>
			<Set name="02" date_pic="" date_vid="2012-08-24" tags=""/>
		</Sets>
	</Model>
	
	<Model firstname="VIP" lastname="" birthdate="" tags="">
		<Sets>
			<Set name="99" date_pic="2012-08-24" date_vid="2012-05-18" tags=""/>
			<Set name="113" date_pic="" date_vid="2012-08-24" tags=""/>
		</Sets>
	</Model>
</Models>
